spring:
  application:
    name: boiler-service
    version: @project.version@
  profiles:
    active: home
  webflux:
    base-path: "/home/boiler"

server:
  port: 6200
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:6000/eureka
    fetch-registry: true
    register-with-eureka: true

shelly:
  actor:
    uni.circulation:
      host: 10.78.30.47
      relay: 1
    pro.boiler:
      host: 10.78.30.20
      relay:
        furnace: 0
        hot-water: 1
        heating: 2
    pro.floor:
      host: 10.78.30.89
      relay: 0

logbook:
  format:
    style: http

logging:
  level:
    org.zalando.logbook: trace

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 6007
management:
  server:
    port: 8007

eureka:
  client:
    enabled: false
