spring:
  application:
    name: boiler-service
    version: @project.version@
  profiles:
    active: home
  webflux:
    base-path: "/home/boiler"
  rabbitmq:
    username: guest
    password: guest
    addresses: rabbitmq
    virtual-host: /boiler
    consumer-name: boiler-service-consumer

server:
  port: 6200
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:6000/eureka
    fetch-registry: true
    register-with-eureka: true

shelly:
  actor.uni.circulation.host: 10.78.30.47
---

spring:
  config:
    activate:
      on-profile: local
  rabbitmq:
    username: boiler
    password: boiler
    addresses: 127.0.0.1:49898
    virtual-host: /boiler
    consumer-name: boiler-service-consumer

server:
  port: 6007
management:
  server:
    port: 8007

eureka:
  client:
    enabled: false